services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - frontend
      - backend
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kolyauzumaki
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
    depends_on:
      - db

volumes:
  pgdata:

networks:
  frontend:
  backend: